### ISSUE TITLE
error for running example code gru_onehot.py

### ISSUE THREAD

**Issue by xypan1232** [mp2893/rnn_predict#1]
Hi 
I run the example code as follows, and it gives me some errors, could i ask hot to fix it? thanks.
 python gru_onehot.py sequences.pkl labels.pkl outfile
Loading data ...  done!!
Building the model ...  done!!
Constructing the optimizer ...  done!!
Optimization start !!
Traceback (most recent call last):
  File "gru_onehot.py", line 268, in <module>
    train_GRU_RNN(dataFile=dataFile, labelFile=labelFile, outFile=outFile, inputDimSize=inputDimSize, hiddenDimSize=hiddenDimSize, max_epochs=max_epochs, L2_reg=L2_reg, batchSize=batchSize, use_dropout=use_dropout)
  File "gru_onehot.py", line 245, in train_GRU_RNN
    validAuc = calculate_auc(test_model, validSet)
  File "gru_onehot.py", line 182, in calculate_auc
    auc = roc_auc_score(list(labels), list(scoreVec))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/ranking.py", line 260, in roc_auc_score
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/metrics/ranking.py", line 251, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

**Comment by mp2893** [comment]
Hi xypan123, 

Thanks for your interest in our work.
I am a bit on a tight schedule until next Monday.
I will look into this matter afterwards.

**Comment by mp2893** [comment]
Hi xypan123,

This error is caused when you have only one class in your labels.
The function "roc_auc_score" requires that you provide labels that consist of two classes (0's and 1's).

**Comment by xypan1232** [comment]
Hi Edward,

thanks, maybe i need test on other datasets.

**Comment by GermanGGarzon** [comment]
did this work? should we be using a different dataset for this to work properly?
