### ISSUE TITLE
[Error] python gru_onehot.py sequences.pkl labels.pkl

### ISSUE THREAD

**Issue by Parkjini** [mp2893/rnn_predict#2]
When I execute gru_onehot.py, I get a below error.

  File "gru_onehot.py", line 211
    print 'Loading data ... ',
                                      ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by mp2893** [comment]
The error message is pretty clear.
If you google that error message, [this](https://stackoverflow.com/questions/25445439/what-does-syntaxerror-missing-parentheses-in-call-to-print-mean-in-python) is the very first result.
