### ISSUE TITLE
Application of Medical Concept Vector

### ISSUE THREAD

**Issue by Ankit267** [mp2893/rnn_predict#3]
Hello Ed,

Our team is working on EMR/EHR data and then applying Machine learning to build models to classify/predict for a specific use cases.
We have gone through your various works such as MedGAN, Medical concept vector using skip-gram and Med2Vec and are really interested in leveraging the same in our experiments.

There are two challenges that we face -
1) Capturing the temporality of data.
2) Deal with large number of features (Diagnosis , medications, Procedures, observations etc.)

We understand that Med2Vec is a better approach than MCV(Skip-gram) as Med2Vec captures the temporality by capturing visit-level representation. 

We wanted to understand more on the Medical concept vector , how we can generate medical concept vectors for any EHR data.
Is MCV with skipgram code is already available  on github?As we understand that you are using emb.pkl pickle files in your python code .

Thanks,
Ankit

**Comment by mp2893** [comment]
Hi Ankit,

I should be accurate to tell you that Med2Vec captures the sequential nature of EHR, but not the actual temporal nature of EHR. People visit hospitals irregularly, but Med2Vec ignores the fact that one neighboring visit might be from a month ago, but another neighboring visit could be a year after.
That being said, it is still a better approach than vanilla skip-gram for the reason you said.

Actually, Med2Vec embeddings are available on my personal webpage. At the bottom of my webpage, there is a section named "Healthcare Concept Representation Learned by Med2Vec". Maybe you can give that a try.

Thanks,
Ed

**Comment by Ankit267** [comment]
Thanks Ed for your reply. Its really helpful!!!!
